// <auto-generated />
namespace CRM.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class vs104 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vs104));
        
        string IMigrationMetadata.Id
        {
            get { return "201612300252333_vs104"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
